# Generated by Django 5.1 on 2024-09-10 11:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CLOCKED_IN', 'Clocked In'), ('NOT_CLOCKED_IN', 'Not Clocked In')], default='ASSIGNED', max_length=20)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to='shift.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clocked_in', models.DateTimeField()),
                ('clocked_out', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DurationField(blank=True, null=True)),
                ('assigned_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='shift.assignedshift')),
                ('clocked_in_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clocked_in_by', to=settings.AUTH_USER_MODEL)),
                ('clocked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clocked_out_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
