# Generated by Django 5.1 on 2024-09-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0005_alter_shift_options_shift_end_date_shift_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='max_employees',
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
    ]
