# Generated by Django 5.1 on 2024-09-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Full_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Modified_Access',
            field=models.BooleanField(default=False),
        ),
    ]
