# Generated by Django 5.1 on 2024-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0002_user_full_access_user_modified_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGE', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=10),
        ),
    ]
