# Generated by Django 5.1 on 2024-09-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_access',
            field=models.BooleanField(default=True),
        ),
    ]
