# Generated by Django 5.1 on 2024-09-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0003_alter_user_email_alter_user_full_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
