# Generated by Django 5.1 on 2024-09-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0007_user_send_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_access',
            field=models.BooleanField(default=False),
        ),
    ]
