# Generated by Django 5.1 on 2024-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0010_alter_user_first_name_alter_user_full_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager')], default='MANAGER', max_length=10),
        ),
    ]
